#!/bin/bash
DIR="$(dirname "$(readlink -f "$0")")"
do_abort() {
  >&2 echo "$@"
  exit 1
}
ensure_file () {
  if [ ! -f "$DIR/$1" ]; then
    do_abort "File not found: $DIR/$1"
  fi
}

# Detect OS and set library path variable
if [[ "$OSTYPE" == "darwin"* ]]; then
  # macOS
  export DYLD_LIBRARY_PATH="$DIR/lib"
  libname="libz3.dylib"
else
  # Linux and others
  export LD_LIBRARY_PATH="$DIR/lib"
  libname="libz3.so"
fi

ensure_file "lib/$libname"
ensure_file "bin/cu-to-json"
ensure_file "bin/faial-drf"
exec "$DIR/bin/faial-drf" --cu-to-json "$DIR/bin/cu-to-json" "$@"

